before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    env:
      # needed for sqlite support
      - CGO_ENABLED=1
    ldflags:
      - "-extldflags=-static"
    tags:
      - sqlite_omit_load_extension
    goos:
      - linux
      # not able to build for these plattforms, as sqlite needs cgo
      #- windows
      #- darwin
    goarch:
      # not able to build ARM or i386, as sqlite needs cgo
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
